#####
name: reg
CycleGAN: True #Unidirectional or bidirectional
TranPAT: True   # With or without registration network
noise_level: 0  #  noise level
port: 8059   #  port parameters
save_root: '/public2/zhongyutian/RSAF-GAN/weights/reg/' #weights
image_save: '/public2/zhongyutian/RSAF-GAN/reg_result/'

# lamda weight
Adv_lamda: 3
Cyc_lamda: 10
Corr_lamda: 20
Smooth_lamda: 10
#LCC_lamda: 5
GCC_lamda: 10
Bend_lamda: 5

epoch: 0        # starting epoch
n_epochs: 100       # How often do you want to display output images during training
batchSize: 1               # size of the batches
dataroot: '/public2/zhongyutian/RSAF-GAN/reg_data/train2D/'     # train data
val_dataroot: '/public2/zhongyutian/RSAF-GAN/reg_data/val2D/'  # val data
lr: 0.0001                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 300                # size of the data crop
input_nc: 1         #输入图片的通道数
output_nc: 1            #输出图片的通道数
cuda: True                
n_cpu: 1

